improved step status handling

diff --git a/.github/workflows/BuildAndRun.yml b/.github/workflows/BuildAndRun.yml
--- a/.github/workflows/BuildAndRun.yml
+++ b/.github/workflows/BuildAndRun.yml
@@ -359,12 +359,6 @@ jobs:
         run: |
           "$buildAndRunScriptPath" run ${{ env.buildDirectory }}
 
-      - name: Set additional step status
-        shell: bash
-        working-directory: ${{ matrix.project }}
-        run: |
-          echo "additionalStepStatus=0" >> "$GITHUB_ENV"
-
       - name: Run with valgrind
         shell: bash
         continue-on-error: true
@@ -373,13 +367,10 @@ jobs:
         run: |
           set +e
           "$buildAndRunScriptPath" run ${{ env.buildDirectory }} valgrind
-          stepStatus=$?
+          valgrindStatus=$?
           set -e
-          echo "stepStatus: [$stepStatus]"
-          if [ "$stepStatus" != "0" ]; then
-            echo "additionalStepStatus=$stepStatus" >> "$GITHUB_ENV"
-          fi
-          echo "additionalStepStatus: [$additionalStepStatus]"
+          echo "valgrindStatus: [$valgrindStatus]"
+          echo "valgrindStatus=$valgrindStatus" >> "$GITHUB_ENV"
             
       - name: Build and Run with Address Sanitizer
         shell: bash
@@ -393,13 +384,10 @@ jobs:
           "$buildAndRunScriptPath" build ${{ env.buildDirectory }} ${{ env.buildType }}
           "$buildAndRunScriptPath" install ${{ env.buildDirectory }} ${{ env.buildType }}
           "$buildAndRunScriptPath" run ${{ env.buildDirectory }}
-          stepStatus=$?
+          asanStatus=$?
           set -e
-          echo "stepStatus: [$stepStatus]"
-          if [ "$stepStatus" != "0" ]; then
-            echo "additionalStepStatus=$stepStatus" >> "$GITHUB_ENV"
-          fi
-          echo "additionalStepStatus: [$additionalStepStatus]"
+          echo "asanStatus: [$asanStatus]"
+          echo "asanStatus=$asanStatus" >> "$GITHUB_ENV"
             
       - name: Build and Run with Memory Sanitizer
         shell: bash
@@ -413,13 +401,10 @@ jobs:
           "$buildAndRunScriptPath" build ${{ env.buildDirectory }} ${{ env.buildType }}
           "$buildAndRunScriptPath" install ${{ env.buildDirectory }} ${{ env.buildType }}
           "$buildAndRunScriptPath" run ${{ env.buildDirectory }}
-          stepStatus=$?
+          msanStatus=$?
           set -e
-          echo "stepStatus: [$stepStatus]"
-          if [ "$stepStatus" != "0" ]; then
-            echo "additionalStepStatus=$stepStatus" >> "$GITHUB_ENV"
-          fi
-          echo "additionalStepStatus: [$additionalStepStatus]"
+          echo "msanStatus: [$msanStatus]"
+          echo "msanStatus=$msanStatus" >> "$GITHUB_ENV"
             
       - name: Build and Run with Thread Sanitizer
         shell: bash
@@ -433,13 +418,10 @@ jobs:
           "$buildAndRunScriptPath" build ${{ env.buildDirectory }} ${{ env.buildType }}
           "$buildAndRunScriptPath" install ${{ env.buildDirectory }} ${{ env.buildType }}
           "$buildAndRunScriptPath" run ${{ env.buildDirectory }}
-          stepStatus=$?
+          tsanStatus=$?
           set -e
-          echo "stepStatus: [$stepStatus]"
-          if [ "$stepStatus" != "0" ]; then
-            echo "additionalStepStatus=$stepStatus" >> "$GITHUB_ENV"
-          fi
-          echo "additionalStepStatus: [$additionalStepStatus]"
+          echo "tsanStatus: [$tsanStatus]"
+          echo "tsanStatus=$tsanStatus" >> "$GITHUB_ENV"
             
       - name: Build and Run with Undefined Behavior Sanitizer
         shell: bash
@@ -453,13 +435,10 @@ jobs:
           "$buildAndRunScriptPath" build ${{ env.buildDirectory }} ${{ env.buildType }}
           "$buildAndRunScriptPath" install ${{ env.buildDirectory }} ${{ env.buildType }}
           "$buildAndRunScriptPath" run ${{ env.buildDirectory }}
-          stepStatus=$?
+          ubsanStatus=$?
           set -e
-          echo "stepStatus: [$stepStatus]"
-          if [ "$stepStatus" != "0" ]; then
-            echo "additionalStepStatus=$stepStatus" >> "$GITHUB_ENV"
-          fi
-          echo "additionalStepStatus: [$additionalStepStatus]"
+          echo "ubsanStatus: [$ubsanStatus]"
+          echo "ubsanStatus=$ubsanStatus" >> "$GITHUB_ENV"
             
       - name: Run with Clang Static Analyzer
         shell: bash
@@ -470,13 +449,10 @@ jobs:
           echo "Running Clang Static Analysis..."
           set +e
           "$buildAndRunScriptPath" cleanAndConfigureWithClangStaticAnalyzer "${{ env.buildDirectory }}" "${{ env.buildType }}" "Ninja"
-          stepStatus=$?
+          clangStaticAnalysisStatus=$?
           set -e
-          echo "stepStatus: [$stepStatus]"
-          if [ "$stepStatus" != "0" ]; then
-            echo "additionalStepStatus=$stepStatus" >> "$GITHUB_ENV"
-          fi
-          echo "additionalStepStatus: [$additionalStepStatus]"
+          echo "clangStaticAnalysisStatus: [$clangStaticAnalysisStatus]"
+          echo "clangStaticAnalysisStatus=$clangStaticAnalysisStatus" >> "$GITHUB_ENV"
             
       - name: Build and Run with Static Analyzers
         shell: bash
@@ -490,15 +466,53 @@ jobs:
           "$buildAndRunScriptPath" build ${{ env.buildDirectory }} ${{ env.buildType }}
           "$buildAndRunScriptPath" install ${{ env.buildDirectory }} ${{ env.buildType }}
           "$buildAndRunScriptPath" run ${{ env.buildDirectory }}
-          stepStatus=$?
+          otherStaticAnalysisStatus=$?
           set -e
-          echo "stepStatus: [$stepStatus]"
-          if [ "$stepStatus" != "0" ]; then
-            echo "additionalStepStatus=$stepStatus" >> "$GITHUB_ENV"
-          fi
-          echo "additionalStepStatus: [$additionalStepStatus]"
+          echo "otherStaticAnalysisStatus: [$otherStaticAnalysisStatus]"
+          echo "otherStaticAnalysisStatus=$otherStaticAnalysisStatus" >> "$GITHUB_ENV"
           
       - name: Check overall additional step status
         shell: bash
         run: |
-          exit $additionalStepStatus
+          overallStepStatus=0
+          echo "Checking linting errors..."
+          echo "valgrindStatus: [$valgrindStatus]"
+          if [ "$valgrindStatus" != "0" ]; then
+            echo "Valgrind failed, so the overall step status is set to failed."
+            overallStepStatus=1
+          fi
+          echo "asanStatus: [$asanStatus]"
+          if [ "$asanStatus" != "0" ]; then
+            echo ASAN failed, so the overall step status is set to failed."
+            overallStepStatus=1
+          fi
+          echo "msanStatus: [$msanStatus]"
+          if [ "$msanStatus" != "0" ]; then
+            echo "MSAN failed, so the overall step status is set to failed."
+            overallStepStatus=1
+          fi
+          echo "tsanStatus: [$tsanStatus]"
+          if [ "$tsanStatus" != "0" ]; then
+            echo "TSAN failed, so the overall step status is set to failed."
+            overallStepStatus=1
+          fi
+          echo "ubsanStatus: [$ubsanStatus]"
+          if [ "$ubsanStatus" != "0" ]; then
+            echo "UBSAN failed, so the overall step status is set to failed."
+            overallStepStatus=1
+          fi
+          echo "clangStaticAnalysisStatus: [$clangStaticAnalysisStatus]"
+          if [ "$clangStaticAnalysisStatus" != "0" ]; then
+            echo "Clang Static Analysis failed, so the overall step status is set to failed."
+            overallStepStatus=1
+          fi
+          echo "otherStaticAnalysisStatus: [$otherStaticAnalysisStatus]"
+          if [ "$otherStaticAnalysisStatus" != "0" ]; then
+            echo "Other Static Analysis failed, so the overall step status is set to failed."
+            overallStepStatus=1
+          fi
+          echo "overallStepStatus: [$overallStepStatus]"
+          if [ $overallStepStatus != "0" ]; then
+            echo "There were issues found in other steps."
+          fi
+          exit $overallStepStatus
